### PR TITLE
Point to new sites and archive old github.io page

### PR DESCRIPTION
**Pull request by nathalie-ckc**
I just updated index.html to point to the OpenAMP Wiki and the new website.

Right now, OpenAMP Wiki might have more useful info than the new
website, so offering both options instead of doing a redirect.

I've also got a PR open on OpenAMP/website to copy over the files from this repository, so that we can just manage them all over there.

### CODE REVIEW

**Comment by arnopo** [comment]
@wmamills, i can not figure out why i can not add you directly as reviewer...
please consider in the reviewer list and review it also ;-)

**Review by arnopo — APPROVED** [review]
LGTM

**Review by edmooring — APPROVED** [review]
Looks good to me.

**Comment by wmamills** [comment]
Yes, I think it is fine also.  Sorry for the delay.

**Comment by arnopo** [comment]
@nathalie-ckc could we merge it? i think you should have the right

**Comment by nathalie-ckc** [comment]
Hi @arnopo ,
Looks like I don't have the merge rights.  I just see a message "This branch has no conflicts with the base branch. Only those with write access to this repository can merge pull requests."  Please could you merge it for me or enable permissions for me?
Thanks & regards,
Nathalie

**Pull request merged**
